name: Post Daily Weather

# スケジュールと手動実行トリガーを設定
on:
  schedule:
    # UTC: 23:00 毎日 → JST の 08:00
    - cron: '0 22 * * *'
  workflow_dispatch:  # GitHub 上で手動トリガー可能にするオプション

jobs:
  post_weather:
    name: 天気予報画像をSlackへ投稿
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Python 環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) 依存ライブラリのインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) スクリプト実行
      - name: Post weather image to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python post_weather.py
