name: Post Daily Weather

on:
  schedule:
    # UTC 22:00 → JST 07:00
    - cron: '0 22 * * *'
    # UTC 10:00 → JST 19:00
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  post_weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Post weather image to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python post_weather.py
